# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - shorman-api

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      SOLUTION_PATH: shorman-api/ShormanServicesBackend.sln
      PROJECT_PATH: shorman-api/ShormanServicesBackend/ShormanServicesBackend.csproj

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build with dotnet
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --no-build -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E5F3061B8BE74EFBB149C27F0B2BD445 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAA1F564CF484EDA811F395D719CF439 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A7C69846ED64369AE3D1E7CE90C19ED }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shorman-api'
          slot-name: 'Production'
          package: .
          